import './globals.css';

import { TodoContextProvider } from "@/context/Todo.context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}) {
  return (
    <html lang="en">
      <body> 
        <TodoContextProvider>{children}</TodoContextProvider>
      </body>
    </html>
  );
}
